version: '3.8'

services:
  game:
    build: .
    ports:
      - "8511:8511"
    volumes:
      - .:/app
      - /app/node_modules 
    command: ["npm", "run", "dev", "--", "--host", "--port", "8511"]